---
title: "code"
output: html_document
---

#PREPROCESSING

## Data reading

```{r}
data <- read.csv('train.csv')
invalid_cols = c(1, 2) #TODO: ELEGIR COLUMNAS QUE NO USAREMOS, de momento 1 y 2
data <- data[, -invalid_cols]
colnames(data)[ncol(data)] <- "Satisfaction"
head(data)
```

## Transforming to categorical variables

```{r}
#Ages  category:value -> 1:0-12, 2:13-30, 3:31-60, 4:61-inf
data$Age[data$Age<=12] <- 1
data$Age[data$Age>12 & data$Age<=30] <- 2 
data$Age[data$Age>30 & data$Age<=60] <- 3 
data$Age[data$Age>60] <- 4 

make.names(c("satisfied", "neutral or dissatisfied"), unique=TRUE)
data$Satisfaction[data$Satisfaction=='neutral or dissatisfied'] <- 'dissatisfied'
head(data['Satisfaction'])

```


## Missing values and outliers

```{r}
na_count <-sapply(data, function(y) sum(length(which(is.na(y)))))
print(na_count[na_count>0])

#Arrival delay is the unique variable with missing values, specifically 310.   #TODO: ¿BORRAMOS LA VARIABLE?

#TODO: buscar outliers ¿que métodos hay?
```

## Data visualization


```{r}
#Balance check

#Satisfaction balance
library(ggplot2)
sat_bal <- ggplot(data = data, aes(x=Satisfaction, fill=Satisfaction)) + 
  geom_bar() + 
  labs(x="Satisfaction balance") +
  theme_minimal()+
  guides(fill=FALSE)
sat_bal

#Gender balance
gen_bal <-ggplot(data = data, aes(x=Gender, fill=Gender)) + 
  geom_bar() + 
  labs(x="Gender balance") +
  theme_minimal()+
  guides(fill=FALSE)
gen_bal

#Age balance
#1:0-12, 2:13-30, 3:31-60, 4:61
age_bal <-ggplot(data = data, aes(x=Age, fill=Age)) + 
  geom_bar() + 
  labs(x="Age") +
  theme_minimal()
age_bal


##Satisfaction comparatives by variable

#Satisfaction vs gender
sat_gen <-ggplot(data = data, aes(x=Gender, fill=Satisfaction)) + 
  geom_bar(position="dodge") + 
  labs(x="Satisfaction vs gender") +
  theme_minimal()
sat_gen

#Satisfaction vs customer type
sat_customer <- ggplot(data = data, aes(x=Customer.Type, fill=Satisfaction)) + 
  geom_bar(position="dodge") + 
  labs(x="Satisfaction vs customer type") +
  theme_minimal()+
  guides()
sat_customer


#Satisfaction vs type of travel
sat_traveltype <- ggplot(data = data, aes(x=Type.of.Travel, fill=Satisfaction)) + 
  geom_bar(position="dodge") + 
  labs(x="Satisfaction vs type of travel") +
  theme_minimal()+
  guides()
sat_traveltype

#Satisfaction vs Class
sat_traveltype <- ggplot(data = data, aes(x=Class, fill=Satisfaction)) + 
  geom_bar(position="dodge") + 
  labs(x="Satisfaction vs Class") +
  theme_minimal()+
  guides()
sat_traveltype

#Satisfaction vs Age
sat_traveltype <- ggplot(data = data, aes(x=Age, fill=Satisfaction)) + 
  geom_bar(position="dodge") + 
  labs(x="Satisfaction vs age") +
  theme_minimal()+
  guides()
sat_traveltype
```


##Transforming to categorical variables
```{r}
data$Gender <- as.numeric(factor(data$Gender, levels = c('Male','Female')))
data$Customer.Type <- as.numeric(factor(data$Customer.Type, levels = c('Loyal Customer','disloyal Customer')))
data$Type.of.Travel <- as.numeric(factor(data$Type.of.Travel, levels = c('Business travel','Personal Travel')))
data$Class <- as.numeric(factor(data$Class, levels = c('Business', 'Eco', 'Eco Plus')))
data$Satisfaction <- factor(data$Satisfaction, levels = c('satisfied', 'dissatisfied'))
unique(data["Satisfaction"])
str(data['Satisfaction'])
```

##Correlation Matrix
```{r}
#IMPORTANTE install.packages("reshape")
library(reshape)
cormat <- round(cor(data),2)
melted_cormat <- melt(cormat)
melted_cormat <- melt(cormat)
ggplot(data = melted_cormat, aes(x=X1, y=X2, fill=value)) + 
  geom_tile() +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1))
  coord_fixed()

```

#TÉNICAS DE CLASIFICACIÓN
```{r}
head(data["Satisfaction"])
```

##TÉCNICAS VISTAS EN CLASE:
```{r}
library(lattice)
library(ggplot2)
library(caret)
library(magrittr)
```
#Cross-validation
```{r}
data_train <- read.csv('train.csv')
data_test <- read.csv('test.csv')
data_total <- rbind(data_train,data_test, deparse.level=1)
```


```{r}
myControl_clas <- trainControl(
  method = "cv",
  number = 10,
  summaryFunction = twoClassSummary,
  classProbs = TRUE, # IMPORTANT!
  savePredictions = TRUE,
  verbose = FALSE
)
```
#GENERALIZED LINEAR MODEL
```{r}
model_clas_glm <- train(Satisfaction~ .,data,
                        method="glm",
                        na.action = na.pass,  #incluyendo esto, elimina el primer error en el que dice que faltan objectos
                        trControl=myControl_clas)

model_clas_glm
```
#GLMNET
```{r}
model_class_glmnet <- train(Satisfaction~ .,data,
                            method = "glmnet",
                            na.action = na.pass,
                            trControl = myControl_clas)
#Error in lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs, : NA/NaN/Inf en llamada a una función externa (arg 5)

```



```{r}
model_clas_xgbTree <- train(Satisfaction~ .,data,
                            method = "xgbTree",
                            na.action = na.pass,
                            trControl=myControl_clas)

```


```{r}
results_xgbTree <- model_clas_xgbTree['results']
which.max(model_clas_xgbTree$results$ROC)
#108 0.9934
summary(model_clas_xgbTree$results)
model_clas_xgbTree$results[108,]
```
##Comparativa de modelos

```{r}
model_list <- list(
   glm = model_clas_glm, 
#  glmnet = ___________________,
#  glmnet_tunning = ___________________,
   xgbTree = model_clas_xgbTree
 )

resamples <- resamples(model_list)

summary(resamples, metric="ROC")

bwplot(resamples, metric = "ROC") 
# display univariate visualizations of the resampling distributions
dotplot(resamples, metric="ROC")

```















